wandb_version: 1

architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: EuroSAT_RGB
bs:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715183314
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 51
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 51
      - 53
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      - 38
      4: 3.10.12
      5: 0.17.0
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
